import Pokemon from '@/components/Pokemon'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

export default function Details() {
  const {
    query: { id },
  } = useRouter()

  const [pokemon, setPokemon] = useState<Pokemon | null>(null)

  useEffect(() => {
    if (!id) return
    fetch(`https://jherr-pokemon.s3.us-west-1.amazonaws.com/pokemon/${id}.json`)
      .then((res) => res.json())
      .then((data) => setPokemon(data))
  }, [id])

  if (!pokemon) return null

  return (
    <main>
      <Head>
        <title>{pokemon?.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Pokemon pokemon={pokemon} />
    </main>
  )
}
