import Pokemon from '@/components/Pokemon'
import Head from 'next/head'

export async function getServerSideProps({
  params,
}: {
  params: { id: string }
}) {
  const { id } = params
  console.log(`id`, id)
  const res = await fetch(
    `https://jherr-pokemon.s3.us-west-1.amazonaws.com/pokemon/${id}.json`
  )
  const pokemon = await res.json()
  return {
    props: {
      pokemon,
    },
  }
}

export default function Details({ pokemon }: { pokemon: Pokemon }) {
  return (
    <main>
      <Head>
        <title>{pokemon?.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Pokemon pokemon={pokemon} />
    </main>
  )
}
