import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Link from 'next/link'

const TO: 'clientside' | 'serverside' | 'staticsite' = `staticsite`

// export async function getServerSideProps() {
//   if (TO === `serverside`) {
//     const res = await fetch(
//       'https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json'
//     )
//     const pokemons = await res.json()
//     return {
//       props: {
//         pokemons,
//       },
//     }
//   }
//   return {
//     props: {},
//   }
// }

export async function getStaticProps() {
  const res = await fetch(
    'https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json'
  )
  const pokemons = await res.json()
  return {
    props: {
      pokemons,
    },
  }
}

export default function Home({ pokemons }: { pokemons: Pokemon[] }) {
  const [pokemonsClient, setPokemonsClient] = useState([])

  useEffect(() => {
    if (TO === `clientside`) {
      fetch('https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json')
        .then((res) => res.json())
        .then((data) => setPokemonsClient(data))
    }
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          maxWidth: '1200px',
          margin: '0 auto',
        }}
      >
        <section
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(4, minmax(200px, 1fr))',
            gridGap: '1rem',
          }}
        >
          {(TO === `clientside` ? pokemonsClient : pokemons)?.map((p: any) => (
            <div
              key={p.id}
              style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <Link href={`/${TO}/pokemon/${p.id}`}>
                <Image
                  src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${p.image}`}
                  alt={p.name}
                  width={200}
                  height={200}
                />
                <h3>{p.name}</h3>
              </Link>
            </div>
          ))}
        </section>
      </main>
    </>
  )
}
