import Pokemon from '@/components/Pokemon'
import Head from 'next/head'
import { useRouter } from 'next/router'

// This function gets called at build time
export async function getStaticPaths() {
  const res = await fetch(
    'https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json'
  )
  const pokemons = await res.json()

  // Get the paths we want to pre-render based on posts
  const paths = pokemons.map((pokemon: any) => ({
    params: { id: pokemon.id.toString() },
  }))
  console.log(`paths`, paths)
  return {
    paths,
    fallback: true,
  }
}

export async function getStaticProps({ params }: { params: { id: string } }) {
  const { id } = params

  const res = await fetch(
    `https://jherr-pokemon.s3.us-west-1.amazonaws.com/pokemon/${id}.json`
  )
  const pokemon = await res.json()
  return {
    props: {
      pokemon,
    },
    revalidate: 10,
  }
}

export default function Details({ pokemon }: { pokemon: Pokemon }) {
  const router = useRouter()

  if (router.isFallback) {
    return <div>Loading...</div>
  }

  return (
    <main>
      <Head>
        <title>{pokemon?.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Pokemon pokemon={pokemon} />
    </main>
  )
}
